### ISSUE TITLE
Better code

### ISSUE THREAD

**Issue by TheEZIC** [cyperdark/osu-api-extended#1]
https://github.com/cyperdark/osu-api-extended/blob/f5fc393e7a36b7fbe99ce65cb97710829f8e71e6/index.js#L203-L204
Здесь можно использовать регулярку с скобочными группами для улучшения качества кода

**Comment by cyperdark** [comment]
Сделал получше:
`let pure = d.display_html.replace(/<[^>]*>?/gm, '').trim();`
ID's из /u/ и /b/ не нужны, потому что id игрока написано выше, а beatmap id мапы есть ниже event.id.diff
