### ISSUE TITLE
pp_calc always returning null

### ISSUE THREAD

**Issue by minidomo** [cyperdark/osu-api-extended#10]
Inputting any beatmap id into `pp_calc` will always return `null`. Example below.

```js
const data = await tools.pp_calc(3555372);
console.log(data); // null
```
I performed a GET request without using `pp_calc` to the corresponding url, https://pp.osuck.net/pp?id=3555372, which worked fine.

**Comment by cyperdark** [comment]
should be fixed

**Comment by minidomo** [comment]
Seems to be working for me. Closing now.
