### ISSUE TITLE
can't seem to get user.scores to work the way I want it too

### ISSUE THREAD

**Issue by MorgenAnSpyrys** [cyperdark/osu-api-extended#12]
Hi there, 
this is probably just me being an ape but I'm trying to figure out how to fetch the entirety of a user's top100 scores. I set the limit for user.scores.category to 100 but it still only ever gives me 5 scores. 
![image](https://user-images.githubusercontent.com/111236657/202257912-18530d51-e299-4154-984e-915e40965bfe.png)
![image](https://user-images.githubusercontent.com/111236657/202258105-0771912d-2598-4e10-b666-47928d70482a.png)
Please let me know in what way I'm being hare-brained here. I originally wanted to DM you instead of opening an issue but you have DMs closed on both twitter and discord. Thanks :)

edit: i also tried using the offset parameter but that didn't work either, i feel like a complete ape for not being able to get it to work 
![image](https://user-images.githubusercontent.com/111236657/202262708-6032bba4-f52c-438c-b7b6-a145439df76d.png)

edit2: upon further investigation i haven't been able to get any params to work for this method. It also seems like a default limit of 5 is hard-coded somewhere I couldn't find (since the api defaults to 10). I assume this mystery code is also what is preventing any other params from applying, but I really have no clue. I have been able to temporarily get my code working by hardcoding my parameters into the url in category.js.

ok i'm stupid and i figured it out, closing

**Comment by cyperdark** [comment]
oops, i did mistake in documentation, thats how it should be
```js
await v2.user.scores.category(user: number, type: 'recent' | 'best' | 'firsts' | 'pinned', obj: {
  include_fails?: string,
  mode?: string,
  limit?: number,
  offset?: string,
})
```

```js
await v2.user.scores.category(user,  'recent', {
  include_fails: true,
  mode: 0,
  limit: 50,
  offset: 0,
})
```

**Comment by cyperdark** [comment]
hello?

**Comment by MorgenAnSpyrys** [comment]
Sorry I didn't notice you reopened the issue, as mentioned when I originally closed it I figured it out (it was the solution you posted) I just assumed it was down to me not being familiar with node (or js in general)

**Comment by cyperdark** [comment]
ah, i see, it's also my fault for mistakes in docs
