### ISSUE TITLE
mods filter

### ISSUE THREAD

**Issue by yorunoken** [cyperdark/osu-api-extended#14]
make a mods filter for plays. like { mods: ["DT", "HD"] } and it would only return plays with dthd, dt, or hd in them. or you can make it return just dthd

**Comment by cyperdark** [comment]
to which endpoints?

**Comment by yorunoken** [comment]
answered u on discord but scores.user.category is the one I want, you can implement it to other endpoints if you so wish.

**Comment by cyperdark** [comment]
done, install 2.7.2
