### ISSUE TITLE
incorrect beatmap sets total property

### ISSUE THREAD

**Issue by ChervyachokMigo** [cyperdark/osu-api-extended#20]
beatmaps sets requests "total" property shows incorrect value at second and more times.

if request second time or after that by cursor_string "total" property of response will equals "10 000" always.

it happens if query set undefined

![image](https://github.com/cyperdark/osu-api-extended/assets/74270643/68ca7329-33fb-47b6-937b-486286d39737)

**Comment by cyperdark** [comment]
thats not issue in this package, it's [osu-web](https://github.com/ppy/osu-web/issues) send this number
