### ISSUE TITLE
responses from v2.beatmaps.search contains not full pool of maps

### ISSUE THREAD

**Issue by ChervyachokMigo** [cyperdark/osu-api-extended#22]
v2.beatmaps.search response not fully pool of maps, all beatmaps which not responsed are blocked by DMCA.
beatmaps and beatmapsets counts on pictures: 
at first - beatmaps all, osu, taiko, fruits, mania, and then beatmapsets: all, osu, taiko, fruits, mania.

first pic: beatmaps count from responses of api v1,
![image](https://github.com/cyperdark/osu-api-extended/assets/74270643/9beedde6-4849-4f33-8275-cef54078fe71)
second pic beatmaps count from responses of  v2.beatmaps.search function
![image](https://github.com/cyperdark/osu-api-extended/assets/74270643/79fd58f3-5137-4dde-a916-dfd19c600b40)

beatmaps difference in csv: (md5 is private db index, ranked is remapped value, gamemode beatmap and sets is equals bancho)
[difference.csv](https://github.com/cyperdark/osu-api-extended/files/14391730/difference.csv) (so now it's list of blocked maps xD)

**Comment by cyperdark** [comment]
thats not issue in this package, it's [osu-web](https://github.com/ppy/osu-web/issues) send maps
