### ISSUE TITLE
Cannot authenticate for the 'chat.write' scope.

### ISSUE THREAD

**Issue by CookyNdi** [cyperdark/osu-api-extended#26]
Hello there,
It might just be a simple oversight, but I'm encountering some issues with authentication while attempting to send a chat message.

Here's the code :

```js
const result = await v2.chat.new(userId, message);
```

And i'm getting this error:

```js
{
     "error": "A required scope is missing."
}
```

Then i'm tried adding authentication:

```js
// chat.ts
await osuAuth(['chat.write']);
const result = await v2.chat.new(userId, message);

// auth.ts
export const osuAuth = async (scope: auth_scopes) => {
  const res = await auth.login(OSU_CLIENT_ID, OSU_CLIENT_SECRET, scope);
  console.log(res);
};
```

And received this response:

```js
{
    "authentication": "basic"
},
```

note : 
I encounter no issues when using the function for a beatmap with "public" scope, but when I attempt to add a scope for chat, some problems arise.

**Comment by cyperdark** [comment]
you need to login via login_lazer

**Comment by CookyNdi** [comment]
I attempted to log in via lazer just now it worked, but nothing happened with chat v2.chat.new.
```js  
const message = 'hi';
const userId = '16983379';
await lazerLogin();
const result = await v2.chat.new(userId, message);
  ```
If I console the result, it is just an empty string.

note :
every time i make a request with lazer auth i keep getting a verification email from osu

**Comment by cyperdark** [comment]
> every time i make a request with lazer auth i keep getting a verification email from osu

cache auth token and reuse it later on, until it expires


> If I console the result, it is just an empty string.

is message sended to user?

**Comment by CookyNdi** [comment]
> is message sended to user?

No, no new messages coming into the id i entered

**Comment by cyperdark** [comment]
will look tomorrow what is wrong
<br>

for now, can you try making a token caching, and after verify latest auth, and then try running request again, maybe it'll fix it

**Comment by CookyNdi** [comment]
I tried to save the previous token in a file, I also verified it by clicking the link in the email
```ts
// chat.ts
const token = readTokenFromFile();
if (!token || token.expires_in < Date.now()) {
  await lazerLogin();
}
console.log({ token });
const result = await v2.chat.new(userId, message);

// auth.ts
export const lazerLogin = async () => {
  const res = await auth.login_lazer('', '');
  saveTokenToFile(res);
  console.log('lazer', res);
};
```

but still getting this error
`"error": "A required scope is missing."`

i not really understand how auth work in this part

**Comment by GabuTheDev** [comment]
> but still getting this error `"error": "A required scope is missing."`

Hi! Iirc all auth methods require a scope array. In `auth.login_lazer()` it's the last parameter. `["public"] ` should do just fine.

**Comment by CookyNdi** [comment]
> In auth.login_lazer() it's the last parameter. ["public"]  should do just fine.

it's getting error
![image](https://github.com/user-attachments/assets/59ef5cb1-62d6-41a7-9738-fcb4fb2a9f49)

**Comment by cyperdark** [comment]
i just checked, and it's working


1. auth with caching token
2. confirm account verification in email
3. restart the code

```js
const { auth, v2 } = require('osu-api-extended');
const fs = require('fs');


const lazer_auth = async () => {
  const txtPath = 'token2.txt';
  if (fs.existsSync(txtPath)) {
    const token = fs.readFileSync(txtPath, 'utf8');

    auth.set_v2(token);
    return
  };


  const cli = await auth.login_lazer(nickname, password);
  console.log(cli);

  fs.writeFileSync(txtPath, cli.access_token, 'utf8');
};


async function main() {
  try {
    await lazer_auth();

    const result = await v2.chat.new(2070907, 'hi');
    console.log(result);

  } catch (error) {
    console.log(error);

  };
};

main();
```

**Comment by CookyNdi** [comment]
thank you so much, i'm just missing `auth.set_v2(token);`
