### ISSUE TITLE
Missing API endpoint for all user beatmap scores

### ISSUE THREAD

**Issue by Tunnelbliick** [cyperdark/osu-api-extended#6]
Currently the API endpoint to retreive all user plays on a specific beatmap is not implemented.

[https://osu.ppy.sh/docs/index.html#get-a-user-beatmap-scores](https://osu.ppy.sh/docs/index.html#get-a-user-beatmap-scores)

The implemented API Point beatmap.scores.user only retrieves a single Score Object which isnt sufficient for my usecase.

**Comment by cyperdark** [comment]
im sorry for big delay, for some reasons i didnt get notification about issue

so i added endpoint, if you find anything else working wrong then let me know
