### ISSUE TITLE
How to automatically refresh OAuth token?

### ISSUE THREAD

**Issue by KeziahMoselle** [cyperdark/osu-api-extended#7]
Not an issue but title.

Do I need to run my own interval to refresh the access token?
Because it seems like the library does not support auto refresh

**Comment by KeziahMoselle** [comment]
Seems like it is not possible to run an interval since `cache_token` is never being invalidated since it just checks for a truthy value.

https://github.com/cyperdark/osu-api-extended/blob/master/src/api/v2/index.ts#L21

What I did for a project is something along thoses lines:

```js
if (
    (this.tokenExpire && new Date() > this.tokenExpire) ||
    !this.tokenExpire
  ) {
    console.log('osu! API v2 access_token is expired or needs to be created')
    await this.getToken()
  }
```

**Comment by cyperdark** [comment]
oh, let me added this

**Comment by Tunnelbliick** [comment]
With the API login osu should return 

```
{
    "access_token": "verylongstring",
    "expires_in": 86400,
    "refresh_token": "anotherlongstring",
    "token_type": "Bearer"
}
```
technically you can use the `refresh_token` if the lease expires to instantly request a new `access_token`. This is probanly a better way of doing it then to compleatly relogging like proposed.

But from what ive seen so far the `refresh_token` gets compleatly thrown away.

**Comment by cyperdark** [comment]
i guess auto refresh is working but i can't test it properly, and also there new way to auth
now will make a migrate.md for it and will push

**Comment by cyperdark** [comment]
new version is published

migration https://github.com/cyperdark/osu-api-extended/blob/master/changes/2.1.2.md

**Comment by KeziahMoselle** [comment]
Nice thanks @cyperdark!

**Comment by KeziahMoselle** [comment]
So I tried running my server for more than 24 hours and it was yielding the auth error, Is it a me problem or it doesn't seem to work? :(

**Comment by cyperdark** [comment]
hmm, let me see

**Comment by cyperdark** [comment]
new version is out

**Comment by KeziahMoselle** [comment]
![image](https://user-images.githubusercontent.com/9168097/160193422-f3d0c2c5-444d-4729-9245-5c6b58004b4a.png)
@cyperdark after 24 hours 😢 (I am calling the auth method before each API call)

**Comment by cyperdark** [comment]
bruh, i guess i need to run debug for a 24 hours to see why its failing

**Comment by cyperdark** [comment]
update the package, i hope this one will work

**Comment by cyperdark** [comment]
i have not that much time to test/work on package, so i make a temporary fix. Will try to fix it later when i finish one thing

**Comment by KeziahMoselle** [comment]
Sure thing don't worry
Updated, will let you know!

**Comment by KeziahMoselle** [comment]
Look like it works with this temp fix 👍

**Comment by cyperdark** [comment]
nice to hear that

**Comment by cyperdark** [comment]
i pushed new version, could i ask you to test it (was complete rewrited)

also docs are look better now https://github.com/cyperdark/osu-api-extended/wiki

some sort of migration https://github.com/cyperdark/osu-api-extended/blob/master/changes/2.5.0.md

**Comment by KeziahMoselle** [comment]
Do I still need to call `auth.login()` in each of my files? From what I've seen, you are relogging if the request yield the auth error, does that mean I can just run `auth.login()` in my root file and everywhere else just doing resources calls ?

**Comment by cyperdark** [comment]
once, in any files and then it will work in any files
